### ISSUE TITLE
0.8.5.2 - Some builds have problems syncing

### ISSUE THREAD

**Issue by meeh420** [Anoncoin/oldrepo-backup#13]
Title ^. More info later.

**Comment by meeh420** [comment]
Seems to be caused because of the rapid decrease in the diff.

These are two examples of clients reporting getting stuck on:

http://explorer.anoncoin.net/block/ffa22d68ba7f5d372406fc651e30a5ff366046cf52ef4088a287827f8b415623
http://explorer.anoncoin.net/block/dc85fc4b7e5312a25e51fa8aba309a0ef03f9a2a92c132af91238fd3ac87e8c1

**Comment by ghost** [comment]
Hi,
i have problems syncing with Block 85487.
http://explorer.anoncoin.net/block/a82195fb3160b58d976cf4b3627aa99eb7eb1f8f167c750a9d6bc7cf47b33a73

It don't syncs and hangs on this block.
Any solution?

Git Version: v0.6.1-1983-ga40bf2e-dirty-beta

compiled with gcc-4.7.3

**Comment by ghost** [comment]
For me, the git version from 09.10. fixes my sync problem.
Thx! :)
