### ISSUE TITLE
Error: cannot find -li2psam and -lboost_chrono

### ISSUE THREAD

**Issue by TheZenKitteh** [Anoncoin/oldrepo-backup#21]
Final Edit: The following is how it should work on Ubuntu at least (the working directory is optional of course):

sudo apt-get install libqtgui4 qt4-qmake libqt4-dev build-essential libboost-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev libssl-dev libdb++-dev git libboost-all-dev libminiupnpc-dev libminiupnpc8
cd $HOME
mkdir Anoncoin
cd Anoncoin
git clone https://github.com/Anoncoin/anoncoin.git
cd anoncoin
qmake
cd i2psam
make -f makefile.unix
cd ..
make

---

EDIT: I have fixed my own problem, here is how.

Between the commands qmake and make, add
cd i2psam
make -f makefile.unix
cd ..

EDIT2: No idea why the below text is so large and bold

Also the sudo apt-get line should also include the libboost-all-dev (probably don't need all but that is what I did to be sure) along with the libminiupnpc-dev libminiupnpc8 in readme-qt.rst
# 

I am attempting to build the QT gui and I got the following error for which I cannot figure out.

I did a:
sudo apt-get install libqtgui4 qt4-qmake libqt4-dev build-essential libboost-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev libssl-dev libdb++-dev git miniupnpc-dev

git clone https://github.com/Anoncoin/anoncoin.git
qmake
make

g++ -fstack-protector -fstack-protector-all -fstack-protector -fstack-protector-all -Wl,-O1 -o anoncoin-qt build/bitcoin.o build/bitcoingui.o build/transactiontablemodel.o build/addresstablemodel.o build/optionsdialog.o build/sendcoinsdialog.o build/addressbookpage.o build/signverifymessagedialog.o build/aboutdialog.o build/editaddressdialog.o build/bitcoinaddressvalidator.o build/version.o build/sync.o build/util.o build/netbase.o build/key.o build/script.o build/main.o build/init.o build/net.o build/irc.o build/checkpoints.o build/addrman.o build/db.o build/walletdb.o build/json_spirit_writer.o build/json_spirit_value.o build/json_spirit_reader.o build/clientmodel.o build/guiutil.o build/transactionrecord.o build/optionsmodel.o build/monitoreddatamapper.o build/transactiondesc.o build/transactiondescdialog.o build/bitcoinstrings.o build/bitcoinamountfield.o build/wallet.o build/keystore.o build/transactionfilterproxy.o build/transactionview.o build/walletmodel.o build/bitcoinrpc.o build/rpcdump.o build/rpcnet.o build/rpcrawtransaction.o build/overviewpage.o build/csvmodelwriter.o build/crypter.o build/sendcoinsentry.o build/qvalidatedlineedit.o build/bitcoinunits.o build/qvaluecombobox.o build/askpassphrasedialog.o build/protocol.o build/notificator.o build/qtipcserver.o build/rpcconsole.o build/scrypt.o build/miningpage.o build/noui.o build/showi2paddresses.o build/i2poptionswidget.o build/i2p.o build/hash.o build/moc_bitcoingui.o build/moc_transactiontablemodel.o build/moc_addresstablemodel.o build/moc_optionsdialog.o build/moc_sendcoinsdialog.o build/moc_addressbookpage.o build/moc_signverifymessagedialog.o build/moc_aboutdialog.o build/moc_editaddressdialog.o build/moc_bitcoinaddressvalidator.o build/moc_clientmodel.o build/moc_guiutil.o build/moc_optionsmodel.o build/moc_monitoreddatamapper.o build/moc_transactiondesc.o build/moc_transactiondescdialog.o build/moc_bitcoinamountfield.o build/moc_transactionfilterproxy.o build/moc_transactionview.o build/moc_walletmodel.o build/moc_overviewpage.o build/moc_csvmodelwriter.o build/moc_sendcoinsentry.o build/moc_qvalidatedlineedit.o build/moc_qvaluecombobox.o build/moc_askpassphrasedialog.o build/moc_notificator.o build/moc_miningpage.o build/moc_rpcconsole.o build/moc_showi2paddresses.o build/moc_i2poptionswidget.o build/qrc_bitcoin.o    -L/usr/lib/i386-linux-gnu -lminiupnpc -lrt -lssl -lcrypto -ldb_cxx -li2psam -Li2psam -lboost_system -lboost_filesystem -lboost_program_options -lboost_thread -lboost_chrono -lQtGui -lQtCore -lpthread 
/usr/bin/ld: cannot find -li2psam
/usr/bin/ld: cannot find -lboost_chrono
collect2: error: ld returned 1 exit status
make: **\* [anoncoin-qt] Error 1

**Comment by yhaenggi** [comment]
for the chrono fix see here -> https://github.com/Anoncoin/anoncoin/blob/master/anoncoin-qt.pro#L389
build the cli first, then then qt (as the makefile.unix probperly builds i2psam)

**Comment by yhaenggi** [comment]
Closing, for i2psam see #23

**Comment by danweller18** [comment]
THANK YOU
