### ISSUE TITLE
Error when trying to run anoncoin-qt on Fedora

### ISSUE THREAD

**Issue by KrzysiekJ** [Anoncoin/oldrepo-backup#22]
The following error is printed on the console and in a popup dialog (along with “A fatal error occured. Anoncoin can no longer continue safely and will quit.” message). Anoncoin then fails to start.

```
EXCEPTION: 9key_error       
CKey::CKey() : EC_KEY_new_by_curve_name failed       
anoncoin in Runaway exception
```

I have Fedora 19 and compiled anoncoin-qt on master branch (commit d36ff9d17c1c81abce697b922). `yum list installed | grep openssl` shows:

```
openssl.x86_64                        1:1.0.1e-30.fc19                  @updates
openssl-compat-bitcoin.x86_64         1:1.0.1e-5ec.fc19                 @bitcoin
openssl-compat-bitcoin-devel.x86_64   1:1.0.1e-5ec.fc19                 @bitcoin
openssl-compat-bitcoin-libs.x86_64    1:1.0.1e-5ec.fc19                 @bitcoin
openssl-devel.x86_64                  1:1.0.1e-30.fc19                  @updates
openssl-libs.i686                     1:1.0.1e-30.fc19                  @updates
openssl-libs.x86_64                   1:1.0.1e-30.fc19                  @updates
```

, where “bitcoin” repository means http://linux.ringingliberty.com/bitcoin/ .

`yum list installed | grep boost` shows that I have boost 1.53.0-14.fc19

**Comment by meeh420** [comment]
Thanks for a great bug report! I'll look into it.

**Comment by KrzysiekJ** [comment]
As suggested on IRC, I’ve removed 32 bit openssl package and recompiled anoncoin-qt, but with no effect.

**Comment by thesharp** [comment]
@KrzysiekJ removing 32bit packages doesn't have a single thing to do with that issue. It's going on because Fedora's OpenSSL doesn't have elliptical curves built in inside of it. You need to manually fetch openssl sources, compile it, install it somewhere in /usr/local and point your wallet's makefile to it. Then everything will work.

**Comment by KrzysiekJ** [comment]
It seems that the Makefile doesn’t fully respect custom openssl path (`OPENSSL_INCLUDE_PATH` and `OPENSSL_LIB_PATH` variables) and the following part should be blamed:

```
obj/scrypt.o: scrypt.c
        gcc -c -o $@ $^
```

The newer versions of Litecoin use `scrypt.cpp` instead of `scrypt.c`, so one way to fix this would be to merge Litecoin changes.

I’ve manually executed `gcc -c -I/opt/openssl-compat-bitcoin/include -l/opt/openssl-compat-bitcoin/lib -o obj/scrypt.o scrypt.c` and a binary is then generated, but I get an error:

```
./anoncoind: relocation error: ./anoncoind: symbol ECDSA_do_sign, version libcrypto.so.10 not defined in file libcrypto.so.10 with link time reference
```

A temporary solution may be to use [custom openssl packages for Fedora](https://people.xiph.org/~greg/openssl/).

**Comment by Gnos1s** [comment]
Is this issue fixed?
