### ISSUE TITLE
Anoncoin-qt make error

### ISSUE THREAD

**Issue by JsonSam** [Anoncoin/oldrepo-backup#30]
$ make
cd /home/usr/anoncoin-d/src/leveldb && CC=gcc CXX=g++ make OPT="-m64 -pipe -fstack-protector-all -D_FORTIFY_SOURCE=2 -O2" libleveldb.a libmemenv.a
make[1]: Entering directory `/home/usr/anoncoin-d/src/leveldb'

make[1]: `libleveldb.a' is up to date.

make[1]: `libmemenv.a' is up to date.

make[1]: Leaving directory `/home/jefferson/anoncoin-d/src/leveldb'

cd /home/usr/anoncoin-d; /bin/sh share/genbuild.sh /home/jefferson/anoncoin-d/build/build.h
/usr/bin/rcc -name bitcoin src/qt/bitcoin.qrc -o qrc_bitcoin.cpp

g++ -c -m64 -pipe -fstack-protector-all -D_FORTIFY_SOURCE=2 -O2 -D_REENTRANT -fdiagnostics-show-option -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -Wstack-protector -DQT_WEBKIT -DQT_GUI -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DENABLE_WALLET -DUSE_UPNP=1 -DSTATICLIB -DUSE_IPV6=1 -DHAVE_BUILD_INFO -DLINUX -D_FILE_OFFSET_BITS=64 -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Isrc -Isrc/json -Isrc/qt -Ii2psam -Isrc/leveldb/include -Isrc/leveldb/helpers -Ibuild -Ibuild -o build/qrc_bitcoin.o qrc_bitcoin.cpp

g++ -m64 -fstack-protector-all -Wl,-O1 -o anoncoin-qt build/anoncoin.o build/bitcoingui.o build/transactiontablemodel.o build/addresstablemodel.o build/optionsdialog.o build/sendcoinsdialog.o build/coincontroldialog.o build/coincontroltreewidget.o build/addressbookpage.o build/signverifymessagedialog.o build/aboutdialog.o build/editaddressdialog.o build/bitcoinaddressvalidator.o build/alert.o build/version.o build/sync.o build/util.o build/hash.o build/netbase.o build/key.o build/script.o build/main.o build/init.o build/net.o build/bloom.o build/checkpoints.o build/addrman.o build/db.o build/walletdb.o build/clientmodel.o build/guiutil.o build/transactionrecord.o build/optionsmodel.o build/monitoreddatamapper.o build/transactiondesc.o build/transactiondescdialog.o build/bitcoinstrings.o build/bitcoinamountfield.o build/wallet.o build/keystore.o build/transactionfilterproxy.o build/transactionview.o build/walletmodel.o build/walletview.o build/walletstack.o build/walletframe.o build/anoncoinrpc.o build/rpcdump.o build/rpcnet.o build/rpcmining.o build/rpcwallet.o build/rpcblockchain.o build/rpcrawtransaction.o build/overviewpage.o build/csvmodelwriter.o build/crypter.o build/sendcoinsentry.o build/qvalidatedlineedit.o build/bitcoinunits.o build/qvaluecombobox.o build/askpassphrasedialog.o build/protocol.o build/notificator.o build/paymentserver.o build/rpcconsole.o build/irc.o build/i2p.o build/scrypt.o build/noui.o build/leveldb.o build/txdb.o build/splashscreen.o build/showi2paddresses.o build/i2poptionswidget.o build/setupdarknet.o build/moc_bitcoingui.o build/moc_transactiontablemodel.o build/moc_addresstablemodel.o build/moc_optionsdialog.o build/moc_sendcoinsdialog.o build/moc_coincontroldialog.o build/moc_coincontroltreewidget.o build/moc_addressbookpage.o build/moc_signverifymessagedialog.o build/moc_aboutdialog.o build/moc_editaddressdialog.o build/moc_bitcoinaddressvalidator.o build/moc_clientmodel.o build/moc_guiutil.o build/moc_optionsmodel.o build/moc_monitoreddatamapper.o build/moc_transactiondesc.o build/moc_transactiondescdialog.o build/moc_bitcoinamountfield.o build/moc_transactionfilterproxy.o build/moc_transactionview.o build/moc_walletmodel.o build/moc_walletview.o build/moc_walletstack.o build/moc_walletframe.o build/moc_overviewpage.o build/moc_csvmodelwriter.o build/moc_sendcoinsentry.o build/moc_qvalidatedlineedit.o build/moc_bitcoinunits.o build/moc_qvaluecombobox.o build/moc_askpassphrasedialog.o build/moc_notificator.o build/moc_paymentserver.o build/moc_rpcconsole.o build/moc_macnotificationhandler.o build/moc_splashscreen.o build/moc_showi2paddresses.o build/moc_i2poptionswidget.o build/qrc_bitcoin.o    -L/usr/lib/x86_64-linux-gnu -lminiupnpc

 /home/usr/anoncoin-d/src/leveldb/libleveldb.a /home/jefferson/anoncoin-d/src/leveldb/libmemenv.a -lrt -lssl -lcrypto -ldb_cxx -Li2psam -li2psam -lboost_system -lboost_filesystem -lboost_program_options -lboost_thread -lpthread -lQtGui -lQtNetwork -lQtCore 
build/init.o: file not recognized: File truncated
collect2: ld returned 1 exit status

make: **\* [anoncoin-qt] Error 1

**Comment by yhaenggi** [comment]
please edit your post and format it properly, thast the least you can do for getting help ;)

**Comment by meeh420** [comment]
build/init.o: file not recognized: File truncated
Never seen that error before, I will try to recreate it. What OS are you running? Linux, but what distro :)

**Comment by yhaenggi** [comment]
just remove build/init.o and build from scratch, this should fix it. this usually happens when your compiling and cancel the build, but the *.o isnt being written in full.
if this dosnt solve it, pls reopen this issue.
