### ISSUE TITLE
Is anoncoin daemon can be used for transactions?

### ISSUE THREAD

**Issue by EMRJ** [Anoncoin/oldrepo-backup#32]
getinfo shows following error

{
"version" : "v0.8.5.1-114-g86f4d89-beta",
...
"errors" : "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"
}

Gives following warning repeatedly after starting the daemon:
Failed to connect to SAM(111)
Created a new SAM session (KSQTJN)  from another (HKUNX)
Closing SAM session (KSQTJN) ...
Failed to connect to SAM(111)

I want to know whether the daemon is reliable to use transactions?

**Comment by Gnos1s** [comment]
Please use the binaries at https://anoncoin.net/ and try again. If you still see this, please open another issue.
