### ISSUE TITLE
i2psam isnt being build by qmake

### ISSUE THREAD

**Issue by dllud** [Anoncoin/oldrepo-backup#33]
I have just cloned the master branch 86f4d89bb4ab7091b194c8eba3db1629f1929223 and I am still affected by #23.

```
> qmake-qt4 "USE_UPNP=-" "USE_BOOST_46=1"
> make
[...]
/usr/bin/ld: cannot find -li2psam
```

I had to go for the workaround described on #21.

**Comment by yhaenggi** [comment]
duplicate of #23
