### ISSUE TITLE
libzerocoin cmake configuration is out of date (zerocoin branch)

### ISSUE THREAD

**Issue by Gnos1s** [Anoncoin/oldrepo-backup#35]
I'm not too familiar with CMake, so I have been editing the GNU makefiles in src/libzerocoin/Build-gcc (these were generated by CMake and have warnings about not making manual changes, which I ignored :) ).

It would be nice to have CMakeLists.txt be up to date and working well with Anoncoin's build system.

**Comment by mikalv** [comment]
I will fix it.

**Comment by mikalv** [comment]
I'm moving the ZC implementation into the new codebase, just disabled. Gonna start with the client mods.

**Comment by Gnos1s** [comment]
Fixed, thanks!
