### ISSUE TITLE
NO BLOCK REWARDS!?

### ISSUE THREAD

**Issue by djspacedevil** [Anoncoin/oldrepo-backup#36]
WHY i become no block rewards?

Diff is 162.34 ... 
2014-08-04 23:29:11 [Pool]  [anoncoin](Thread 7) Share accepted at diff 46.4516129/952.75728865 by ASXtddi1r59hywKjd3x1r3uw************\* [77.**_.**_.**]

But the block was not send to the blockchain, what is wrong?!?

**Comment by yhaenggi** [comment]
either the diff calc of your miner is wrong, or the block got orphaned. of course there could be tons of other errors wrt miner.
please submit debug log of your miner (there you see whats happening). and take a look at ~/.anoncoin/debug.log for a new block at given time, post it on pastebin/similiar and il take a look at it.

**Comment by djspacedevil** [comment]
{
    "version" : "v0.8.5.1-121-gfffef88-dirty-beta",
    "protocolversion" : 70007,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "blocks" : 221866,
    "moneysupply" : 1147289.36200000,
    "timeoffset" : -2,
    "connections" : 8,
    "proxy" : "",
    "ip" : "0.0.0.0",
    "difficulty" : 172.44457236,
    "testnet" : false,
    "keypoololdest" : 1406995037,
    "keypoolsize" : 101,
    "paytxfee" : 0.00010000,
    "mininput" : 0.00010000,
    "errors" : "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"

http://pastebin.com/1r5bXGDs

And this say the pool:

2014-08-05 00:43:44 [Pool]  [anoncoin](Thread 5) Share accepted at diff 44.22992928/956.21956863 by ASXtddi1r59hywKjd3x1r3uwXLv9xPG4du ********_]
2014-08-05 00:43:45 [Pool]  [anoncoin](Thread 5) Share accepted at diff 44.22992928/116.48894976 by ASXtddi1r59hywKjd3x1r3uwXLv9xPG4du [**_*****_]
2014-08-05 00:43:46 [Pool]  [anoncoin](Thread 5) Share accepted at diff 44.22992928/52.84395163 by ASXtddi1r59hywKjd3x1r3uwXLv9xPG4du [**_******]

one over the block diff.

Pool: Miner-Control.de

**Comment by yhaenggi** [comment]
nvm about the debug.log, i thougd your solo mining.
As it got accepted, you would have to ask your pool operator.
I recommend using p2pool, this way you wont have problems with pool OPs with bad setups (if we assume this is the case) or OPs which steal coins (alot do that, but only a fraction).

**Comment by djspacedevil** [comment]
Iam the pool admin. So i will make it run for me, and all miners..... im testing it, but when i see shares higher the diff, and no block will found.... i must find the error....

**Comment by yhaenggi** [comment]
Something weird about submitblock, its being called way too often. I assume your pool is using getblocktemplate?

**Comment by djspacedevil** [comment]
Is reward POS?  OR POW?
tx-messages  true?

**Comment by yhaenggi** [comment]
PoW, no tx-messages.
Please check if ur Address prefix is set correct, otherwise your blocks would be stale of course.
See src/base58.h Line 275 for the used prefix

**Comment by djspacedevil** [comment]
The Server validate the address with ThreadRPCServer method=validateaddress
In Pool Log This: 2014-08-05 01:05:57 [Pool]  [anoncoin](Thread 7) Share accepted at diff 84.44444445/580.74902541 by ASXtddi1r59hywKjd3x1r3uwXLv9xPG4du [**.**.**.**]

But in the same time, no log in debug.log file. only "getaccount" and trying connections...

**Comment by yhaenggi** [comment]
According to your pool stats, your hashrate isnt big enough to submit somany blocks. i assume something is wrong with the diff calculation.
Running P2Pool with anoncoin{d,-qt} is working fine and it seems both use getblocktemplate, so getblocktemplate isnt broken.
You find a diff 580 PoW with 459kHs? Repeated blocks with such a low hashrate cant be right, this also points to a difficulty calc problem.

**Comment by djspacedevil** [comment]
So, i have rescan the chain. and now the blocks comes fast in. getblocks 22.... to  000000.... limit 500

i dont now, if this normal.

mh. i setup tomorrow the p2pool to check this. thx.

**Comment by yhaenggi** [comment]
getblocks are fine, nothing to worry about.
