### ISSUE TITLE
Seed nodes to add

### ISSUE THREAD

**Issue by lunokhod** [Anoncoin/oldrepo-backup#40]
# Seed nodes to add:
## I2P
1. Lunokhod: <br>
   TTTXGrUaoWwvb1~AaC1sJyZqepgaRvxAPmdvQGjRs3T-3ZfSUDTMvNkG-6FlHwTK1r~mqOT-QIzYWPWiRkqGCQWe0zbO3M1Pk6M0KcW0C-pEHMin32cf-ctcQtN4iFAhScCFIk55~2Z~9RApQUM-gxkwMenRaRxCyvuXvaHukAsbIs8w4f7x3CP1X6Tw0YUKaixrr6RZlP0T75UgIXD2Y-B8quUq3Jyq63ie4PsNK7dr2HPIaE6H3zMrLR45Jrobllf-e56Wv00dYYa9zyLZ-36a5HLB~utCluRtn~Enm8vrQfWNkRLndQB4kstwZfiqdaHYA~yh0hJ3uupByuqlBmn1hkzM5BZrKtKgf6517bSlG-MpBOUlc4DnrmSsxx~AxaduHPzWtHtQo1xX9DMYNKKJ5jgmRrtANKh9zHM1nPvcDUTksqIW-eJ0Ir2aAskDJPIDtuRvG-7XMm4TJnr1F5jxE3g3MM8gSPgMEnIxid0Zm1ByvbarFecocrr~adv2AAAA<br/><br/>
   7zbwzykhyjcmmessswamkxfyya7hioiy2oq7voaw27625qwruqia.b32.i2p

**Comment by meeh420** [comment]
Awesome, thanks.

**Comment by yhaenggi** [comment]
Please also post who is the owner (nickname on bitcointalk/IRC/github) of said node, otherwise we will get a messy list over time.

**Comment by Cryptoslave** [comment]
1. Cryptoslave:

wV3VH8LCTMrdkf3-qYuEw6BkhC6ChQyczQRxRDRrTFPEUiAipqNGsofXHAmTtF1MzirB2aBeuuHuOszcy3209NNmxr2RZD5Gz~XTyT55Juw2Qoc2VitdeaAwlaLzYIM1z1Amw9yIV43G~~B318N3iaxlNoEPN4YLzpipIl6h6zcDi6pJdLsMO7hKxagKzPLAx6scrui4GsNO6sQ-6eUBpiO3XM~gbE3yag82ShhIsxabTrrSCowqM~nFVNdZ58hBrwSOGpCKZ3-rfrJ3I0-ZFR52CyfZY-O8jasftGMQFF0QpKT60uLwTZwsExBuqYKWumXojdq07B4VO~1w~CprF0OEJpX8Uul2Q-1r7P1ANmWJI8fg~~B1~c7xtfoWW7omd6lNvQRgmuH~w2yQZ59wIuuDMZTmJB4S9dnGbCr0B4G0kAgpuaV9hfVkZzOddsM9e5o0mYJZE1BPCEMTbm817xaRi5DVQMd2bTTO0YRdgXe6wylXo9KyeL-fMbmnD7AbAAAA

xynjl64xlviqhkjl2fbvupj7y3wct46jtayoxm2ksba6tqzo6tsa.b32.i2p

**Comment by yhaenggi** [comment]
Both imported with d353e4bc1c1f43e578f1bef54c11a7ac6552561c
