### ISSUE TITLE
Overview page: balances and recent transaction windows not sized properly (OSX/develop)

### ISSUE THREAD

**Issue by lunokhod** [Anoncoin/oldrepo-backup#49]
The balances and recent transactions windows on the overview page are not being sized correctly on OSX (develop branch). Each window should span ~50% of the page width (as with the bitcoin client), but as they are substantially smaller, the transaction text is being overwritten. 

This image demonstrates the problem:

https://img.bi/#/LQX6rRl!71pGIT4xANJTq5NQ7q6naUEYB6SQ6FeSUOrm7FAj

**Comment by GroundRod** [comment]
Lastest merged commit attempts to repair this problem, let me know how it goes, it is not showing up here as a problem when build with a shared QT 4.6 libary on linux, the changes I just made here seem to work ok on it still, and I'll check that it works ok on a win 32bit build soon.  Hard to debug without your feedback on the Mac build, would not have known there was a problem.
