### ISSUE TITLE
Proposed deletion of outdated branches

### ISSUE THREAD

**Issue by lunokhod** [Anoncoin/oldrepo-backup#51]
_There are a number of branches that are outdated, and which contain no anoncoin authored commits. Several other branches are likely to have been merged into the last release (0.8.6)._

**I propose to delete the following branches:**
~~\* 0.6.2: No anoncoin authored commits. Last commit gavinandresen authored on May 11, 2012~~
~~\* 0.6.3: No anoncoin authored commits. Last commit Greedi authored on Nov 29, 2012~~
~~\* blockheaders: No anoncoin authored commits. Last commit gavinandresan, Oct 2011.~~
~~\* electrum: No anoncoin authored commits. Last commit coblee, July 2012.~~
~~\* freenode-verf: No anoncoin authored commits. Last commit Jeff Garzik, April 2011~~
~~\* master-fix: This branch is up to date with master-0.8~~
~~\* master-neo: The last commit on this branch (march 15 2014) is identical to the same commit on master. Master contains 24 additional commits.~~

**I propose to rename the following branches:**
~~\* master-0.8 --> 0.8.5~~

**The status of the following branches is not clear. I ask that the last author check to see if these are necessary, or it they have already been merged with other branches.**
~~\* 0.8: Last commit meeh420 authored on Oct 12, 2013~~
~~\* master-old: Last commit K1773R authored on Dec 26, 2013 --> renamed 0.7.5~~
~~\* native_i2p: Last commit meeh420 authored on Jun 14, 2013~~
~~\* new_diffcalc: Last commit meeh420 authored on Jun 26, 2013~~
~~\* osx-qt5: Last commit meeh420 authored on Jun 25, 2013~~
~~\* protswitch: Last commit meeh420 authored on Jun 12, 2013~~
- newbase: Last commit meeh420 authored on Oct 2, 2014
- replace_kgw: Last commit Gnos1s authored on Oct 31, 2014
- zerocoin_old: Last commit Gnos1s authored on Oct 19, 2014
- zc: Last commit Gnos1s authored on Aug 7, 2014

**Comment by GroundRod** [comment]
Need to investigate the differences between master and master-neo, was unaware of these extra 10 commits and specifically worked very hard to include valuable concepts in v9 (develop), based on (what I though) was the most recent master branch.  Will post here when I've finished that investigation....

**Comment by GroundRod** [comment]
Just by looking at your research results, I'm good with deleting at least these additional branches...

```
native_i2p: Last commit meeh420 authored on Jun 14, 2013
new_diffcalc: Last commit meeh420 authored on Jun 26, 2013
osx-qt5: Last commit meeh420 authored on Jun 25, 2013
protswitch: Last commit meeh420 authored on Jun 12, 2013
```

Doubt I ever look back and miss them.....

**Comment by GroundRod** [comment]
Been looking at all the master- something branches and gotta say... its a mess to figure out.

Can not give an opinion without allot of additional research.  Did study the differences between master-neo and master, there is possibly some text I want to port to v9, (gotta check), but no code changes that are of importance to our newer work.  Should master-neo -> 0.8?   not sure yet.

As to your proposal on master-0.8 -> 0.8   Pretty sure that is not the best idea, code comparsions I looked at showed it as based on code way back, and probably unusable.  ATM thinking one of the other master- branches should become 0.8, perhaps -neo.

**Comment by GroundRod** [comment]
My thought on branches is this.... 'develop' should soon become master.

As soon as we developers and testers think it's ready to be called that we create a new 0.9.4-rc1 branch off develop (or something like that), put out binaries for that exact version, and the various platforms with that new branch we created from develop.  Then rename 'develop' to 'master' and keep working on improvments and fixes until v0.9.5 is ready.  so on and so forth....

Master should be something that is our latest current work, always builds properly and is up to a standard where we can be happy users are downloading and trying it out, but could have problems as the work is very new...  We may need to create some more offshoots to test out various merged-mining functionality, zerocoin, i2p ideas, but as much as possible I want those to be kept local, and not be faced with this huge problem we have now of deciphering which branch is which.  So if we do need some testing branches they are short lived, and deleted once done, and the proper coding required merged then with master.

So following that logic, master is experimental, but the latest and greatest.  We for sure need to keep and have the best possible v8 branch, changing its name to your proposed: 0.8, is good I think, and fine by me.   Plus various v9 builds is what I was thinking, 9.4, 9.5, 9.6 etc.. versions that are older than the very latest work, but stable and have preformed well with the features we could offer at that time.

We are now well on our way to btc v10 tech, but diverging in several area, more in the near future, so it's hard for me to image what we will call v10 atm.  There is still lots of coding changes to catch up with there now already, and more everyday.  Some we don't need or care about, others would be good to have.  In the meantime, the above ideas is only one of many possible paths.

Any feedback or alternative ideas welcome...
GR

**Comment by lunokhod** [comment]
Concerning develop and master branches, I propose the following:
1. Tag commits in branch develop as "0.9.4-rc1", etc. These should automatically appear under the "releases" link on github. These should be signed with your PGP key.
2. Merge the final 0.9.4 tagged release (in branch develop) into master (if possible).
3. If it is not possible, or too complicated, to merge develop into master: rename branch master to 0.8.6, delete the old master branch, and then create new master branch with the 0.9.4 commit.

**Comment by lunokhod** [comment]
Contacted Meeh by email. If no response by March 4 2015 the following actions will be taken:
- master-old - rename "unknown-master-old"
- native_i2p - delete
- new_diffcalc - delete
- newbase - delete
- osx-qt5 - delete
- protswitch - delete

**Comment by yhaenggi** [comment]
@GroundRod branches arent really needed. we can tag commits as versions.
also tags should be signed with the taggers gpg key.

**Comment by GroundRod** [comment]
Thanks for the ideas and direction we need to go on this.  I had practiced setting a tag on a commit before, however it never showed up on the remote, only locally for me.  Think you've given me the clue as to why, need that gpg key set....
