### ISSUE TITLE
Official binaries

### ISSUE THREAD

**Issue by lunokhod** [Anoncoin/oldrepo-backup#63]
I propose creating the following branches to host official Anoncoin binaries

binaries-osx
binaries-linux
binaries-win32
binaries-win

An example for osx can be found in my personal repo:

https://github.com/lunokhod/anoncoin/tree/binaries-osx

Please read the README file as this will need to be tailored for each platform (they should be as standardized as possible).

Also, please look at the create-sig.sh and verify-sig.sh scripts that verify the gpg detached signatures and sha1 and md5 checksums. This will likely need to be modified for your platform as well. If you have a better way of doing this let me know: we should assume that the average user will not know how to verify these themself without further explanation.

**Comment by lunokhod** [comment]
It's possible that archiving binaries on the anoncoin project might eventually cause disk quota issues. Github states that ~1 Gb per project is ok. Perhaps it would be better to create a new project Anoncoin/anoncoin-binaries, as opposed to creating branches for binaries in Anoncoin/anoncoin. 

Comments?

**Comment by GroundRod** [comment]
Really good point, had forgot about that issue.  Agree putting binaries on Github is a bad idea, at least long term. Wish it wasn't true, but had a thought, could it be setup as a separate project?  Then binaries would not impact our source code needs anytime soon.

Released cross-platform binaries and then adding bootstrap.dat files, even compressed, could push things over that limit pretty fast....  But Anoncoins blockchain is still small enough that it shouldn't be a problem....compressed size I have on it, from a week ago is: 122.7MB

**Comment by lunokhod** [comment]
I just created a new project anoncoin-binaries, and will create the branches osx, linux, windows, windows32. If github complains about the size, it will not be a problem to delete the entire project.

**Comment by Cryptoslave** [comment]
Good job!
