### ISSUE TITLE
"This is a pre-release test build"

### ISSUE THREAD

**Issue by ghost** [Anoncoin/oldrepo-backup#86]
can you please help me..  i want to write a pool/blockchain application.. i want to modify it. i want to detect errors in the "error" string.. but the actual anoncoin version here on github always produces in getinfo the string

```
"version" : "v0.8.5.7",
"protocolversion" : 70007,
"walletversion" : 60000,
"errors" : "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"
```

so how can i the source of the stable version? ( no, i don't want the binary.. ) how can i remove the string?
there is a additional branch "0.8.5" , but it is 2 years old..
the most recent release "v0.8.5.6" is also 2 years old..

**Comment by ghost** [comment]
workaround:
src\clientversion.h , Line 17

```
#define CLIENT_VERSION_IS_RELEASE  true
```

**Comment by Cryptoslave** [comment]
thank you, good work
