### ISSUE TITLE
I2P peer address sharing not efficient enough

### ISSUE THREAD

**Issue by Cryptoslave** [Anoncoin/oldrepo-backup#90]
This is a serious issue. When connecting to a peer A with for instance 6 I2P addresses connected to it, from another peer B, the peer A seemingly do not send the information to peer B about the currently connected I2P peer.

If peer A is 9.6.9, it does not provide the I2P or IPv4 addresses when requested with a "sending: getaddr"

But if peer A is 8.5.6 it then send up to 1000 I2P address it has stored in its peer.dat:

2015-12-21 23:28:12 received 1000 addresses, serialized size 542 bytes each, from peer=4, peeraddr=knbsdahwwkf6kwxmk45qqe57mbsfgldmhi4jdbhnjdzs4xeeuzra.b32.i2p
2015-12-21 23:28:12 Added 3 addresses from knbsdahwwkf6kwxmk45qqe57mbsfgldmhi4jdbhnjdzs4xeeuzra.b32.i2p: 3 tried, 100 new

Then peer B must try all those I2P addresses, many having been dynamic I2P address, and this takes alot of time and is not efficient at all process.

To overcome the issue GroundRod disabled sharing of DYN address in 9.6.9 by default, only sharing STATIC ones. In this way the peers.dat will not overwhelm the I2P nodes with outdated I2P addresses.

But I think it is not enough to ensure a good behaviour on I2P. What is needed is that each I2P peer share not only the peers.dat (after hardfork containing only STATIC addresses, if we ensure peers.dat is not compatible from 8.5.6, which GR may have done already as he changed how they were stored in peers.dat iirc); but, and most importantly, ALL its currently CONNECTED I2P PEERS, both DYN and STATIC, if possible with higher priority than the peers.dat database. And the receiving peer B shall then try FIRST and foremost test those currently connected I2P peers from peer A. Only then will the network be well spread out, especially if many people use DYN, which will be the case when ZC will be out.

To conclude, at the bare minimum to resolve this issue, peer A if it is 0.9.6.9 should answer the "sending: getaddr" message by giving at least the addresses in peer.dat like 0.8.5.6!! And then what would be best is to share the currently connected node with a higher priority.

**Comment by Cryptoslave** [comment]
<Cryptoslave> like I am not sure there really is a bug with 0.9.6.9 and address sharing
<Cryptoslave> because when checking overnight logs it seems it respond correctly to the getaddr command
<Cryptoslave> I checked both 9.6.9 peer connected
<Cryptoslave> 2015-12-22 20:54:32 sending: getaddr (0 bytes) to peer=43, peeraddr=xynjl64xlviqhkjl2fbvupj7y3wct46jtayoxm2ksba6tqzo6tsa.b32.i2p
<Cryptoslave> 2015-12-22 20:54:32 Marking as good failed, expected to find xynjl64xlviqhkjl2fbvupj7y3wct46jtayoxm2ksba6tqzo6tsa.b32.i2p
<Cryptoslave> after this the other xynj peer did not send its address
<Cryptoslave> but
<Cryptoslave> 2015-12-22 20:54:32 sending: addr (543 bytes) to peer=43, peeraddr=xynjl64xlviqhkjl2fbvupj7y3wct46jtayoxm2ksba6tqzo6tsa.b32.i2p
<Cryptoslave> this 969 node responded correctly to request by the same getaddr request from xynj
<Cryptoslave> and later, xynj also sent its addr after a getaddr
<Cryptoslave> so in fact it seems they both send address

But the nodes using 8.5.6 master branch send a list of 3000+ address in peers.dat (both IPv4 and I2P) in package of 1000, I am not sure this is a healthy behaviour neither, too much address to try... So maybe 9.6.9 has the correct behaviour with regard to peers.dat. Still it would be nice if the peers currently connected are shared with a higher priority.

**Comment by Cryptoslave** [comment]
Also there is this code dissimilar in Bitcoin and Anoncoin:

<Cryptoslave> bitcoin https://github.com/bitcoin/bitcoin/blob/master/src/net.cpp#L1584
<Cryptoslave> and
<Cryptoslave> anoncoin https://github.com/Anoncoin/anoncoin/blob/gr_develop/src/net.cpp#L1702
<Cryptoslave> especially lines 1715-1718
<Cryptoslave>             int nNewBias = (nOutbound \* 80) / MAX_OUTBOUND_CONNECTIONS;
<Cryptoslave>             // Keep the max value less than 100%, as the routine expects
<Cryptoslave>             nNewBias = min( nNewBias, 99 );
<Cryptoslave>             CAddress addr = addrman.Select(10 + nNewBias);
<Cryptoslave> I understand it does a loop to try to connect to addresses
<Cryptoslave> but I would like to know why GR did a difference between old tried and new untried addresses and why bitcoin does not care
<Cryptoslave> also especially since the time reported for tried addresses is not correct so the priority may be awkward and this result in not efficient peer finding

2015-12-22 07:16:41 trying connection b7ziruwpk7g2e44xyomnc2nu5tx7bc2f2ai4dzi66uxm3bc3qttq.b32.i2p lastseen=135.3hrs

This is not true I was connected to it a few hour before...

Also this line do not happen often:
2015-12-22 01:09:43 Moving b7ziruwpk7g2e44xyomnc2nu5tx7bc2f2ai4dzi66uxm3bc3qttq.b32.i2p to tried

and regarding this:
2015-12-22 01:12:10 Added 3 addresses from b7ziruwpk7g2e44xyomnc2nu5tx7bc2f2ai4dzi66uxm3bc3qttq.b32.i2p: 2 tried, 45 new
2015-12-22 11:39:06 Added 1 addresses from b7ziruwpk7g2e44xyomnc2nu5tx7bc2f2ai4dzi66uxm3bc3qttq.b32.i2p: 4 tried, 71 new

Tried increase very slowly while new increase much quicker. I think the issue is:
-too much sharing of old nodes (3000+ old addresses from peers.dat from 8.5.6)
-not efficient loop to try more addresses (we can change the number in lines 1715-1718 of https://github.com/Anoncoin/anoncoin/blob/gr_develop/src/net.cpp or remove that routine to put back the Bitcoin one.
-There is not, I think, a sharing of currently connected peers, only from peers.dat

This all result in an overwhelm of bogus nodes and a slow test routine so a poor per sharing, IMO

**Comment by Cryptoslave** [comment]
It appears https://github.com/Anoncoin/anoncoin/blob/gr_develop/src/net.cpp#L1718
 CAddress addr = addrman.Select(10 + nNewBias);
Does not lead to the call to the right function using nUnkBias described at line 1705

Indeed the function to be called is probably this one:
https://github.com/Anoncoin/anoncoin/blob/gr_develop/src/addrman.cpp#L575
CAddress CAddrMan::Select_(int nUnkBias)

So it seems the work is unfinished here, addrman.Select_(int nUnkBias) and addrman.Select(10 + nNewBias) must refer to the same function that permit the correct selection of peer address to try, new or old, based on a random number generator and some algo to choose which new or old node to try.

This function is not to be found in Bitcoin and I do not know if it is pure GR creation or from another altcoin.

What shall we do about this broken/unfinished/not called correctly function? Or we remove it without breaking everything, or we try to finish it and unbug it, and call it correctly, to have the routine correctly set. I think the not efficient trial of nodes must somewhat come from this particular code.

Also with regard to sharing currently connected peers, it seems GR did not want to share info about currently connected peers: https://github.com/Anoncoin/anoncoin/blob/gr_develop/src/addrman.cpp#L414
Is sharing the peers the node is currently connected to an attack vector IYHO?

**Comment by Cryptoslave** [comment]
OK I think we shall at first implement this Bitcoin patch:
https://github.com/sipa/bitcoin/commit/c6a63ceeb4956933588995bcf01dc3095aaeb1fc
and
https://github.com/bitcoin/bitcoin/pull/5941

Later we shall see at which frequency this particular routine is called to try each addresses fetched from addrman and increase it to have higher addresses throughput. Indeed the loop shall stop at 100 trials (https://github.com/Anoncoin/anoncoin/blob/gr_develop/src/net.cpp#L1728) then call for DNSSeed etc, but I dont see the program do this in the log, it only ask for DNSSeed once on startup and not for weeks afterward. Also, the trial of new addresses from addrman is so slow it takes a day or more between them often. So there clearly is an issue with this routine which is not called often enough to be of any use and in fact for 9.6.9 version this result in inefficient peer discovery.

Finally we shall get rid of this sharing of 4000+ old peers.dat addresses from 8.5.6 peers which is overwhelming and aggravate the issue.

**Comment by Cryptoslave** [comment]
The patch discussed above was applied to addrman.cpp and addrman.h (https://github.com/Anoncoin/anoncoin/commit/ec6acc2ca6f1a6df88107911fa029f8b558cb8db and before) and it corrected this issue for IPv4 (https://github.com/Anoncoin/anoncoin/issues/92). Sadly it did not increase the sharing for the onlynet=I2P network!

**Comment by ssua6** [comment]
Hi @Cryptoslave , 

Could you please provide steps on how to reproduce this issue locally? I would appreciate that greatly, thank you.

**Comment by Cryptoslave** [comment]
Well to see it, firstly you connect one peer to i2p network, once/if this peer is connected to several peers (others than the hardcoded ones), you connect to it with another i2p anoncoin instance. You will see poor sharing (ie the non-hardcoded peers will not be detected by the other peer). 

It is difficult to find peers not hardcoded though unless you yourself are a hardcoded peer, like mine. So I can easily test it but for you it is more difficult presently (we have less than 8 i2p peers in total, so only 2 or 3 are not hardcoded...).

What is interesting is to try to type 'destination' in the console. You will see this for instance:

￼
[
{
"tablesize" : 3,
"matchsize" : 3
},
{
"address" : "3mlrhj76653madodmllbnaah5qtkyvxf72xi3mmmxxxn3bwkymia.b32.i2p",
"good" : false,
"attempt" : 0,
"lasttry" : 0,
"connect" : 0,
"source" : "164.132.25.194"
},
{
"address" : "aptabkh5zx62vmcvhss6mwczu6r37ojqwzn7hbtunzhzfqp55e4a.b32.i2p",
"good" : false,
"attempt" : 0,
"lasttry" : 0,
"connect" : 0,
"source" : "128.199.47.200"
},
{
"address" : "srcneruhzymepcflqjrne5fduihwooak5ausg6qs3ugiozh7bhhq.b32.i2p",
"good" : false,
"attempt" : 0,
"lasttry" : 0,
"connect" : 0,
"source" : "84.73.4.183"
}
]

Here we can see that clearnet peers share i2p addresses too.  Most probably the issue is due to a lack of good nodes and an overwhelming number of old nodes that are broadcasted. Best is to first hardfork after adding two more i2p seednodes (to have like 6 of them reachable), then let the new code for i2p addrman cleanup do its thing. If this is still an issue later we can reopen this issue. I close it until then.

**Comment by Cryptoslave** [comment]
Corrected https://github.com/Anoncoin/anoncoin/commit/a700f49543b9c1a4bceb2c9e65cc5b4908fdebf3

**Comment by Cryptoslave** [comment]
Finally bug was found! https://github.com/Anoncoin/anoncoin/commit/44053a1104b37a88ba7fee2f1556346b9fb3cc57
